Data API stuff
mikeshardmind/SinbadCogs pull request #236
Opened 2020-07-17 07:20 UTC by mikeshardmind

While this would be reasonably safe to merge prior to CogCreators/Red-DiscordBot#4045 , that PR is still subject to change.

This PR serves as both the intended way of initially handling this for these cogs, as well as providing an example of what cog creators need to handle, and the sorts of editorial decisions which may apply.

2020-07-19 05:02 UTC, DiscordLiz requested changes
Let's talk about this more later. We have permission from each user to keep logs and data after account deletion already, so if any of this is too much, don't bother with it.

2020-07-19 05:02 UTC, DiscordLiz commented on modnotes/modnotes.py
> +    )
Just move this to the private repo so that people don't use this.

2020-07-19 21:24 UTC, mikeshardmind commented on modnotes/modnotes.py
> +    )
That would be the easier option here. I'm fine marking it as hidden and eventually migrating this to a schema which can tolerate anonymization though.

2020-07-21 00:32 UTC, DiscordLiz commented
you need to update this for your changes to the design.

2020-07-25 20:12 UTC, merged